# Generated by Django 4.2.7 on 2023-11-06 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_winners_app", "0005_alter_comment_comment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 11, 6, 15, 39, 2, 61728)
            ),
        ),
    ]
